services:
  - type: web
    name: real-money-income-bd-v2
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: FIREBASE_DATABASE_URL
        value: https://app-arbooks-default-rtdb.firebaseio.com
      - key: ADMIN_EMAILS
        sync: false
