import express from "express";
import path from "path";
import {fileURLToPath} from "url";
import admin from "firebase-admin";

const __filename=fileURLToPath(import.meta.url);
const __dirname=path.dirname(__filename);
let serviceAccount={};
try{serviceAccount=JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON||"{}")}catch(e){throw new Error("FIREBASE_SERVICE_ACCOUNT_JSON is not valid JSON.")}
if(!serviceAccount.project_id) console.warn("Firebase Admin credentials are missing.");
if(!admin.apps.length&&serviceAccount.project_id) admin.initializeApp({credential:admin.credential.cert(serviceAccount),databaseURL:process.env.FIREBASE_DATABASE_URL||"https://real-money-income-bd-default-rtdb.firebaseio.com"});
const db=()=>admin.database(),app=express();
app.use(express.json({limit:"1mb"}));app.use(express.static(path.join(__dirname,"public")));
const clean=(v,m=500)=>String(v??"").trim().slice(0,m),num=v=>Number(v),now=()=>Date.now();
async function auth(req,res,next){try{const h=req.headers.authorization||"";if(!h.startsWith("Bearer "))return res.status(401).json({error:"Login required"});req.user=await admin.auth().verifyIdToken(h.slice(7));next()}catch(e){res.status(401).json({error:"Invalid or expired login session"})}}
function adminOnly(req,res,next){const a=(process.env.ADMIN_EMAILS||"").split(",").map(x=>x.trim().toLowerCase()).filter(Boolean);if(!req.user?.email||!a.includes(req.user.email.toLowerCase()))return res.status(403).json({error:"Admin access denied"});next()}
async function getSettings(){const s=(await db().ref("settings").get()).val()||{};return {siteName:s.siteName||"Real Money Income BD",welcome:s.welcome||"Work From Home & Earn",withdrawalTaxPercent:Math.max(0,num(s.withdrawalTaxPercent)||0),referralPercent:Math.max(0,num(s.referralPercent)||0),referralFixed:Math.max(0,num(s.referralFixed)||0),minWithdraw:Math.max(0,num(s.minWithdraw)||0),maxWithdraw:Math.max(0,num(s.maxWithdraw)||0),methods:s.methods||{bKash:{enabled:true,label:"bKash",hint:"11 digit bKash number"},Nagad:{enabled:true,label:"Nagad",hint:"11 digit Nagad number"},Rocket:{enabled:true,label:"Rocket",hint:"11 digit Rocket number"},Binance:{enabled:true,label:"Binance ID",hint:"Binance Pay ID / UID"},Bank:{enabled:false,label:"Bank",hint:"Account number"}}}}
function pub(s){return {...s}}
app.get("/api/health",(q,r)=>r.json({ok:true,version:"3.0.0"}));

app.post("/api/profile",auth,async(req,res)=>{const uid=req.user.uid,name=clean(req.body.name,80);if(!name)return res.status(400).json({error:"Name is required"});const ref=db().ref(`users/${uid}`),snap=await ref.get(),old=snap.val()||{};const p={uid,name,email:req.user.email||old.email||"",updatedAt:now()};if(!snap.exists()){p.balance=0;p.status="active";p.role="user";p.verified=false;p.createdAt=now();p.referralCode=uid.replace(/[^a-zA-Z0-9]/g,"").slice(0,8).toUpperCase()||uid.slice(0,8).toUpperCase();const code=clean(req.body.referralCode,100).toUpperCase();if(code){const all=(await db().ref("users").get()).val()||{};for(const [id,u] of Object.entries(all))if(id!==uid&&u.referralCode===code){p.referredBy=id;break}}}await ref.update(p);res.json({ok:true})});
app.get("/api/me",auth,async(req,res)=>{const s=await db().ref(`users/${req.user.uid}`).get();res.json({uid:req.user.uid,email:req.user.email,user:s.val()||null})});
app.get("/api/settings",auth,async(req,res)=>res.json(pub(await getSettings())));
app.get("/api/tasks",auth,async(req,res)=>{const root=(await db().ref("tasks").get()).val()||{};res.json(Object.entries(root).map(([id,t])=>({id,...t})).filter(t=>t.active!==false).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)))});
app.post("/api/tasks/:id/claim",auth,async(req,res)=>{const uid=req.user.uid,id=clean(req.params.id,120),ref=db().ref(`tasks/${id}`),s=await ref.get();if(!s.exists())return res.status(404).json({error:"Task not found"});const t=s.val();if(t.active===false)return res.status(400).json({error:"Task is inactive"});if(t.slots&&num(t.claimed||0)>=num(t.slots))return res.status(400).json({error:"This task is full"});const cr=db().ref(`taskClaims/${uid}/${id}`);if((await cr.get()).exists())return res.status(409).json({error:"Already submitted"});await cr.set({taskId:id,title:clean(t.title,150),reward:num(t.reward)||0,category:clean(t.category,60),status:"pending",createdAt:now()});await ref.update({claimed:(num(t.claimed)||0)+1});res.json({ok:true})});
app.get("/api/transactions",auth,async(req,res)=>{const x=(await db().ref(`transactions/${req.user.uid}`).get()).val()||{};res.json(Object.entries(x).map(([id,t])=>({id,...t})).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)))});
app.post("/api/transactions",auth,async(req,res)=>{const type=clean(req.body.type,20),amount=num(req.body.amount),method=clean(req.body.method,40),reference=clean(req.body.reference,150);if(!["deposit","withdraw"].includes(type))return res.status(400).json({error:"Invalid transaction type"});if(!Number.isFinite(amount)||amount<=0)return res.status(400).json({error:"Invalid amount"});const u=(await db().ref(`users/${req.user.uid}`).get()).val()||{};if(u.status==="blocked")return res.status(403).json({error:"Account is blocked"});if(type==="withdraw"){const s=await getSettings(),m=s.methods?.[method];if(!method||!reference)return res.status(400).json({error:"Payment method and your receiving number/ID are required"});if(!m||m.enabled===false)return res.status(400).json({error:"This payment method is not available"});if(s.minWithdraw&&amount<s.minWithdraw)return res.status(400).json({error:`Minimum withdrawal is ৳${s.minWithdraw}`});if(s.maxWithdraw&&amount>s.maxWithdraw)return res.status(400).json({error:`Maximum withdrawal is ৳${s.maxWithdraw}`});if(amount>num(u.balance||0))return res.status(400).json({error:"Insufficient balance"});const tax=+(amount*s.withdrawalTaxPercent/100).toFixed(2),net=+(amount-tax).toFixed(2),tr=db().ref(`transactions/${req.user.uid}`).push();await tr.set({type,amount,grossAmount:amount,taxPercent:s.withdrawalTaxPercent,tax,netAmount:net,method,reference,status:"pending",createdAt:now()});return res.json({ok:true,id:tr.key,tax,netAmount:net})}const tr=db().ref(`transactions/${req.user.uid}`).push();await tr.set({type,amount,method,reference,status:"pending",createdAt:now()});res.json({ok:true,id:tr.key})});
app.get("/api/referral",auth,async(req,res)=>{const uid=req.user.uid,u=(await db().ref(`users/${uid}`).get()).val()||{},all=(await db().ref("users").get()).val()||{};let count=0;for(const [id,x]of Object.entries(all))if(x.referredBy===uid)count++;const er=(await db().ref(`referralEarnings/${uid}`).get()).val()||{};const earnings=Object.values(er).reduce((a,x)=>a+(num(x.amount)||0),0);res.json({code:u.referralCode||uid.slice(0,8).toUpperCase(),count,earnings})});

/* Admin */
app.get("/api/admin/stats",auth,adminOnly,async(req,res)=>{const users=(await db().ref("users").get()).val()||{},tr=(await db().ref("transactions").get()).val()||{},cl=(await db().ref("taskClaims").get()).val()||{};let dep=0,wd=0,pw=0,pc=0;for(const xs of Object.values(tr))for(const x of Object.values(xs||{})){if(x.type==="deposit"&&x.status==="approved")dep+=num(x.amount)||0;if(x.type==="withdraw"){wd+=num(x.amount)||0;if(x.status==="pending")pw+=num(x.amount)||0}}for(const xs of Object.values(cl))for(const x of Object.values(xs||{}))if(x.status==="pending")pc++;res.json({users:Object.keys(users).length,totalDeposit:dep,totalWithdraw:wd,pendingWithdraw:pw,pendingTasks:pc})});
app.get("/api/admin/settings",auth,adminOnly,async(req,res)=>res.json(await getSettings()));
app.patch("/api/admin/settings",auth,adminOnly,async(req,res)=>{const p={};["siteName","welcome","withdrawalTaxPercent","referralPercent","referralFixed","minWithdraw","maxWithdraw"].forEach(k=>{if(req.body[k]!==undefined)p[k]=typeof req.body[k]==="number"?req.body[k]:clean(req.body[k],200)});if(req.body.methods&&typeof req.body.methods==="object")p.methods=req.body.methods;await db().ref("settings").update(p);res.json({ok:true,settings:await getSettings()})});
app.get("/api/admin/users",auth,adminOnly,async(req,res)=>{const x=(await db().ref("users").get()).val()||{};res.json(Object.entries(x).map(([uid,u])=>({uid,...u})))});
app.patch("/api/admin/users/:uid",auth,adminOnly,async(req,res)=>{const uid=clean(req.params.uid,200),p={};if(req.body.status)p.status=clean(req.body.status,20);if(req.body.balance!==undefined){const b=num(req.body.balance);if(!Number.isFinite(b)||b<0)return res.status(400).json({error:"Invalid balance"});p.balance=b}if(req.body.verified!==undefined)p.verified=!!req.body.verified;if(req.body.role)p.role=clean(req.body.role,20);if(req.body.name)p.name=clean(req.body.name,80);await db().ref(`users/${uid}`).update(p);res.json({ok:true})});
app.post("/api/admin/tasks",auth,adminOnly,async(req,res)=>{const title=clean(req.body.title,150),description=clean(req.body.description,1000),reward=num(req.body.reward),category=clean(req.body.category,60)||"General",slots=Math.max(0,Math.floor(num(req.body.slots)||0));if(!title||!Number.isFinite(reward)||reward<0)return res.status(400).json({error:"Title and valid reward are required"});const r=db().ref("tasks").push();await r.set({title,description,reward,category,slots,claimed:0,active:req.body.active!==false,createdAt:now(),updatedAt:now()});res.json({ok:true,id:r.key})});
app.patch("/api/admin/tasks/:id",auth,adminOnly,async(req,res)=>{const id=clean(req.params.id,120),p={};["title","description","category"].forEach(k=>{if(req.body[k]!==undefined)p[k]=clean(req.body[k],k==="description"?1000:150)});if(req.body.reward!==undefined)p.reward=Math.max(0,num(req.body.reward));if(req.body.slots!==undefined)p.slots=Math.max(0,Math.floor(num(req.body.slots)||0));if(req.body.active!==undefined)p.active=!!req.body.active;p.updatedAt=now();await db().ref(`tasks/${id}`).update(p);res.json({ok:true})});
app.delete("/api/admin/tasks/:id",auth,adminOnly,async(req,res)=>{await db().ref(`tasks/${clean(req.params.id,120)}`).remove();res.json({ok:true})});
app.get("/api/admin/transactions",auth,adminOnly,async(req,res)=>{const root=(await db().ref("transactions").get()).val()||{},o=[];for(const [uid,xs]of Object.entries(root))for(const [id,t]of Object.entries(xs||{}))o.push({uid,id,...t});o.sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));res.json(o)});
app.patch("/api/admin/transactions/:uid/:id",auth,adminOnly,async(req,res)=>{const uid=clean(req.params.uid,200),id=clean(req.params.id,200),action=clean(req.body.action,20),tr=db().ref(`transactions/${uid}/${id}`),tx=(await tr.get()).val();if(!tx)return res.status(404).json({error:"Transaction not found"});if(tx.status!=="pending")return res.status(409).json({error:"Transaction already reviewed"});if(!["approved","rejected"].includes(action))return res.status(400).json({error:"Invalid action"});if(action==="approved"){const ur=db().ref(`users/${uid}`),u=(await ur.get()).val()||{};let b=num(u.balance||0);if(tx.type==="deposit")b+=num(tx.amount);if(tx.type==="withdraw"){if(b<num(tx.amount))return res.status(400).json({error:"User balance is insufficient"});b-=num(tx.amount)}await ur.update({balance:b})}await tr.update({status:action,reviewedAt:now(),reviewedBy:req.user.email});res.json({ok:true})});
app.get("/api/admin/task-claims",auth,adminOnly,async(req,res)=>{const root=(await db().ref("taskClaims").get()).val()||{},o=[];for(const [uid,xs]of Object.entries(root))for(const [id,c]of Object.entries(xs||{}))o.push({uid,id,...c});o.sort((a,b)=>(b.createdAt||0)-(a.createdAt||0));res.json(o)});
app.patch("/api/admin/task-claims/:uid/:id",auth,adminOnly,async(req,res)=>{const uid=clean(req.params.uid,200),id=clean(req.params.id,200),action=clean(req.body.action,20),cr=db().ref(`taskClaims/${uid}/${id}`),c=(await cr.get()).val();if(!c)return res.status(404).json({error:"Claim not found"});if(c.status!=="pending")return res.status(409).json({error:"Already reviewed"});if(!["approved","rejected"].includes(action))return res.status(400).json({error:"Invalid action"});if(action==="approved"){const ur=db().ref(`users/${uid}`),u=(await ur.get()).val()||{};await ur.update({balance:num(u.balance||0)+num(c.reward||0)});if(u.referredBy){const s=await getSettings(),commission=+(num(c.reward||0)*num(s.referralPercent||0)/100+num(s.referralFixed||0)).toFixed(2);if(commission>0){const rr=db().ref(`referralEarnings/${u.referredBy}`).push();await rr.set({fromUser:uid,claimId:id,amount:commission,createdAt:now(),reason:"Approved task referral commission"});const rref=db().ref(`users/${u.referredBy}`),ru=(await rref.get()).val()||{};await rref.update({balance:num(ru.balance||0)+commission})}}}await cr.update({status:action,reviewedAt:now(),reviewedBy:req.user.email});res.json({ok:true})});
app.get("/api/admin/referrals",auth,adminOnly,async(req,res)=>{const users=(await db().ref("users").get()).val()||{},o=[];for(const [uid,u]of Object.entries(users)){const children=Object.entries(users).filter(([id,x])=>x.referredBy===uid).map(([id,x])=>({uid:id,name:x.name,email:x.email})),er=(await db().ref(`referralEarnings/${uid}`).get()).val()||{},earnings=Object.values(er).reduce((a,x)=>a+(num(x.amount)||0),0);o.push({uid,name:u.name,email:u.email,code:u.referralCode||"",count:children.length,earnings,children})}o.sort((a,b)=>b.earnings-a.earnings);res.json(o)});
app.use((req,res)=>req.method==="GET"?res.sendFile(path.join(__dirname,"public","index.html")):res.status(404).json({error:"Not found"}));
const port=process.env.PORT||3000;app.listen(port,()=>console.log(`RMI BD V3 running on ${port}`));